name: RidA Platform CI

on:
  pull_request:
    branches: [ main, development ]

jobs:
  test-and-lint:
    name: Test & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x' # Or the version specified in your package.json
          cache: 'npm' # Set cache for npm

      - name: Install Dependencies
        run: npm install

      # Use the scripts from your root package.json
      - name: Lint All Packages
        run: npm run lint

      - name: Run All Tests
        run: npm run test

      - name: Build All Packages
        run: npm run build